version: '3'
services:

  #PHP Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ${WEB_API_DIR}:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - db
      - redis
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8095:80"
      - "4430:443"
    volumes:
      - ${WEB_API_DIR}:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: kotl_as_root
      MYSQL_DATABASE: kotl
      MYSQL_USER: kotl
      MYSQL_PASSWORD: kotl
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/dbdata:/var/lib/mysql/
      - ./mysql/my.ini:/etc/mysql/my.cnf
    networks:
      - app-network

  #Redis service
  redis:
    container_name: redis
    image: redis:5.0.7
    ports:
      - "6379:6379"

#Docker Networks
networks:
  app-network:
    driver: bridge
